language: node_js
node_js:
  - 10
  - 12
  - 14
env:
  - CXX=g++-4.8

matrix:
  include:
    - name: Lint
      node_js: 12
      script: npm run lint

before_install: 'sudo add-apt-repository -y ppa:inkscape.dev/stable && sudo apt-get install -y g++-4.8 optipng pngcrush pngquant graphicsmagick libjpeg-turbo-progs inkscape libcairo2-dev libgif-dev libjpeg8-dev zlib1g-dev'
script: npm run test:ci
after_success: '<coverage/lcov.info ./node_modules/coveralls/bin/coveralls.js'
